apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackpilot.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.identityService.replicaCount }}
  selector:
    matchLabels:
      app: identity-service
      stackpilot.io/environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: identity-service
        {{- include "stackpilot.commonLabels" . | nindent 8 }}
    spec:
      containers:
        - name: identity-service
          image: "{{ .Values.identityService.image.repository }}:{{ .Values.identityService.image.tag }}"
          imagePullPolicy: {{ .Values.identityService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.identityService.service.port }}
          env:
            - name: ENV
              value: {{ .Values.global.environment | quote }}
            - name: DB_HOST
              value: postgres-identity
            - name: DB_PORT
              value: {{ .Values.postgresIdentity.service.port | quote }}
            - name: DB_NAME
              value: {{ .Values.postgresIdentity.auth.database | quote }}
            - name: DB_USER
              value: {{ .Values.postgresIdentity.auth.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresIdentity.auth.password | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.identityService.probes.readinessPath }}
              port: {{ .Values.identityService.service.port }}
          livenessProbe:
            httpGet:
              path: {{ .Values.identityService.probes.livenessPath }}
              port: {{ .Values.identityService.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.default.requests.cpu }}
              memory: {{ .Values.resources.default.requests.memory }}
            limits:
              cpu: {{ .Values.resources.default.limits.cpu }}
              memory: {{ .Values.resources.default.limits.memory }}