{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackpilot-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.customer }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.customerPortal.name }}
                port:
                  number: 80

    - host: {{ .Values.ingress.hosts.admin }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.adminPortal.name }}
                port:
                  number: 80

    - host: {{ .Values.ingress.hosts.ops }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.opsPortal.name }}
                port:
                  number: 80
{{- end }}