apiVersion: v1
kind: Service
metadata:
  name: ops-portal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackpilot.commonLabels" . | nindent 4 }}
spec:
  selector:
    app: ops-portal
    stackpilot.io/environment: {{ .Values.global.environment }}
  ports:
    - port: {{ .Values.opsPortal.service.port }}
      targetPort: {{ .Values.opsPortal.service.port }}
      protocol: TCP
  type: ClusterIP
