apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.opsPortal.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.opsPortal.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.opsPortal.port }}
  type: ClusterIP