apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-identity
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackpilot.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresIdentity.replicaCount }}
  selector:
    matchLabels:
      app: postgres-identity
      stackpilot.io/environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: postgres-identity
        {{- include "stackpilot.commonLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres-identity
          image: "{{ .Values.postgresIdentity.image.repository }}:{{ .Values.postgresIdentity.image.tag }}"
          imagePullPolicy: {{ .Values.postgresIdentity.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgresIdentity.service.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresIdentity.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresIdentity.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresIdentity.auth.password | quote }}
          resources:
            requests:
              cpu: {{ .Values.resources.default.requests.cpu }}
              memory: {{ .Values.resources.default.requests.memory }}
            limits:
              cpu: {{ .Values.resources.default.limits.cpu }}
              memory: {{ .Values.resources.default.limits.memory }}
