apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wallet.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.wallet.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.wallet.port }}
  type: ClusterIP