apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackpilot.commonLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.walletService.replicaCount }}
  selector:
    matchLabels:
      app: wallet-service
      stackpilot.io/environment: {{ .Values.global.environment }}
  template:
    metadata:
      labels:
        app: wallet-service
        {{- include "stackpilot.commonLabels" . | nindent 8 }}
    spec:
      containers:
        - name: wallet-service
          image: "{{ .Values.walletService.image.repository }}:{{ .Values.walletService.image.tag }}"
          imagePullPolicy: {{ .Values.walletService.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.walletService.service.port }}
          env:
            - name: ENV
              value: {{ .Values.global.environment | quote }}
            - name: PORT
              value: {{ .Values.walletService.service.port | quote }}
            - name: POSTGRES_HOST
              value: postgres-wallet
            - name: POSTGRES_PORT
              value: {{ .Values.postgresWallet.service.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresWallet.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresWallet.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresWallet.auth.password | quote }}
          readinessProbe:
            httpGet:
              path: {{ .Values.walletService.probes.readinessPath }}
              port: {{ .Values.walletService.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: {{ .Values.walletService.probes.livenessPath }}
              port: {{ .Values.walletService.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 6
          resources:
            requests:
              cpu: {{ .Values.resources.default.requests.cpu }}
              memory: {{ .Values.resources.default.requests.memory }}
            limits:
              cpu: {{ .Values.resources.default.limits.cpu }}
              memory: {{ .Values.resources.default.limits.memory }}
