apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stackpilot.commonLabels" . | nindent 4 }}
spec:
  selector:
    app: wallet-service
    stackpilot.io/environment: {{ .Values.global.environment }}
  ports:
    - port: {{ .Values.walletService.service.port }}
      targetPort: {{ .Values.walletService.service.port }}
      protocol: TCP
  type: ClusterIP
