global:
  appName: stackpilot
  environment: dev
  ingressClassName: nginx
  domainSuffix: local

labels:
  owner: stackpilot
  managedBy: helm

resources:
  default:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

identityService:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/identity-service
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8081
  probes:
    readinessPath: /ready
    livenessPath: /health

walletService:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/wallet-service
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8082
  probes:
    readinessPath: /ready
    livenessPath: /health

systemService:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/system-service
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8083
  probes:
    readinessPath: /ready
    livenessPath: /health

customerPortal:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/customer-portal
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8084
  probes:
    readinessPath: /ready
    livenessPath: /health
  ingressHost: customer.local

adminPortal:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/admin-portal
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8085
  probes:
    readinessPath: /ready
    livenessPath: /health
  ingressHost: admin.local

opsPortal:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/paul2409/ops-portal
    tag: "v1"
    pullPolicy: IfNotPresent
  service:
    port: 8086
  probes:
    readinessPath: /ready
    livenessPath: /health
  ingressHost: ops.local

postgresIdentity:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: identitydb
    username: identity
    password: identitypass

postgresWallet:
  enabled: true
  replicaCount: 1
  image:
    repository: postgres
    tag: "15"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    database: walletdb
    username: wallet
    password: walletpass
