global:
  environment: dev
  domainSuffix: local

customerPortal:
  replicaCount: 1
  ingressHost: customer-dev.local

adminPortal:
  replicaCount: 1
  ingressHost: admin-dev.local

opsPortal:
  replicaCount: 1
  ingressHost: ops-dev.local

identityService:
  replicaCount: 1

walletService:
  replicaCount: 1

systemService:
  replicaCount: 1

resources:
  default:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

labels:
  environment: dev