global:
  environment: dev
  domainSuffix: local
  buildTime: "unknown"
identityService:
  replicaCount: 1
  image:
    tag: sha-0f13b5e
walletService:
  replicaCount: 1
  image:
    tag: sha-0f13b5e
systemService:
  replicaCount: 1
  image:
    tag: sha-0f13b5e
customerPortal:
  replicaCount: 1
  ingressHost: customer-dev.local
  image:
    tag: sha-0f13b5e
adminPortal:
  replicaCount: 1
  ingressHost: admin-dev.local
  image:
    tag: sha-0f13b5e
opsPortal:
  replicaCount: 1
  ingressHost: ops-dev.local
  image:
    tag: sha-0f13b5e
resources:
  default:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
labels:
  environment: dev
