Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  # Disable default synced folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Rsync repo into guest
  config.vm.synced_folder "../", "/vagrant",
    type: "rsync",
    rsync__auto: true,
    rsync__exclude: [".git/", ".vagrant/", ".venv/"]

  nodes = [
    { name: "control", ip: "192.168.56.10", memory: 4096, maxmemory: 4096, cpus: 2 },
    { name: "worker1", ip: "192.168.56.11", memory: 2048, maxmemory: 5120, cpus: 3 },
    { name: "worker2", ip: "192.168.56.12", memory: 2048, maxmemory: 5120, cpus: 3 }
  ]

  nodes.each do |node|
    config.vm.define node[:name] do |n|
      n.vm.hostname = node[:name]

      # Lab NIC only. When prompted, choose: StackPilotInternal
      n.vm.network "private_network", ip: node[:ip]

      n.vm.provider "hyperv" do |h|
        h.vmname = "stackpilot-#{node[:name]}"
        h.memory = node[:memory]
        h.maxmemory = node[:maxmemory]
        h.cpus = node[:cpus]
      end

      # Keep provisioners, but script runs them later with `vagrant provision`
      n.vm.provision "shell",
        path: "../scripts/provision/bootstrap.sh",
        privileged: true

      n.vm.provision "shell",
        path: "../scripts/ops/hosts.sh",
        privileged: true
    end
  end
end