#!/usr/bin/env bash
set -euo pipefail

# ----------------------------------------------------------
# PURPOSE
# Runs terraform plan for AWS infra.
# If a per-run override var-file exists (run.tfvars),
# it will be passed explicitly.
# ----------------------------------------------------------

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TF_DIR="${ROOT_DIR}/infra/aws/tf"
AWS_ENV="${ROOT_DIR}/infra/aws/aws.env"

LOG_DIR="${ROOT_DIR}/artifacts/logs/aws"
mkdir -p "${LOG_DIR}"

# ----------------------------------------------------------
# Load AWS environment (profile, region, SSH key default)
# ----------------------------------------------------------
source "${AWS_ENV}"

# ----------------------------------------------------------
# Optional per-run var-file (generated by aws-run-tfvars)
# ----------------------------------------------------------
RUN_TFVARS="${ROOT_DIR}/artifacts/aws/run.tfvars"
VAR_ARGS=()

if [[ -f "${RUN_TFVARS}" ]]; then
  echo "INFO: using run-specific var-file: ${RUN_TFVARS}"
  VAR_ARGS+=("-var-file=${RUN_TFVARS}")
fi

echo "== AWS: terraform plan =="

terraform -chdir="${TF_DIR}" init -upgrade >/dev/null

terraform -chdir="${TF_DIR}" plan \
  -no-color \
  "${VAR_ARGS[@]}" \
  | tee "${LOG_DIR}/aws-plan.log"

echo "PASS: terraform plan"
