apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackpilot

resources:
  - namespace.yaml

  # identity DB
  - postgres-identity/secret.yaml
  - postgres-identity/deployment.yaml
  - postgres-identity/service.yaml

  # wallet DB
  - postgres-wallet/secret.yaml
  - postgres-wallet/deployment.yaml
  - postgres-wallet/service.yaml

  # internal services
  - identity-service/deployment.yaml
  - identity-service/service.yaml

  - wallet-service/deployment.yaml
  - wallet-service/service.yaml

  - system-service/deployment.yaml
  - system-service/service.yaml

  # portals
  - customer-portal/deployment.yaml
  - customer-portal/service.yaml

  - admin-portal/deployment.yaml
  - admin-portal/service.yaml

  - ops-portal/deployment.yaml
  - ops-portal/service.yaml

  - ingress.yaml