apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackpilot-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/paul2409/stackpilot.git
    targetRevision: dev
    path: helm/stackpilot
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stackpilot-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
