apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-service
  template:
    metadata:
      labels:
        app: system-service
    spec:
      containers:
        - name: system-service
          image: ghcr.io/paul2409/system-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: SERVICE_NAME
              value: system-service
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: ENV
              value: dev
            - name: PORT
              value: "8000"
            - name: IDENTITY_SERVICE_URL
              value: http://identity-service:8000
            - name: WALLET_SERVICE_URL
              value: http://wallet-service:8000
            - name: REQUEST_TIMEOUT
              value: "2.0"
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10